var CONST_APPLICATION_VERSION = "0.4";
var CONST_APPLICATION_NAME    = "EPC on Steroids";

var CONST_ACCESS_TOKEN_PROPERTY_NAME = "accessToken";
var CONST_INSTANCE_URL_PROPERTY_NAME = "instanceUrl";
var STRING_EMPTY_STRING_CONST = "";


var CONST_HEADER_ROW_NUMBER = 1;
var CONST_FIRST_DATA_ROW_NUMBER = 3;
var CONST_CHECKED_COLUMN_NUMBER = 1;


var CONST_EXPORT_SCOPE_ENUM = Object.freeze({"INCLUDE_ALL": 1, "INCLUDE_ONLY_CHECKED": 2});
