var CONST_APPLICATION_VERSION = "0.9";
var CONST_APPLICATION_NAME    = "EPC on Steroids";

var CONST_ACCESS_TOKEN_PROPERTY_NAME = "accessToken";
var CONST_INSTANCE_URL_PROPERTY_NAME = "instanceUrl";
var CONST_REFRESH_TOKEN_PROPERTY_NAME = "refreshToken";

var CONST_ORG_TYPE_PROPERTY_NAME = "ORG_TYPE";
var CONST_CUSTOMER_KEY_PROPERTY_NAME = "CUSTOMER_KEY";
var CONST_CUSTOMER_SECRET_PROPERTY_NAME = "CUSTOMER_SECRET";

var CHUNK_SIZE = 50;    

var STRING_EMPTY_STRING_CONST = "";


var CONST_FIRST_HEADER_ROW_NUMBER = 1;
var CONST_FIRST_HEADER_COLUMN_NUMBER = 1;
var CONST_LAST_HEADER_ROW_NUMBER = 2;

var CONST_FIRST_DATA_ROW_NUMBER = 3;
var CONST_FIRST_DATA_COLUMN_NUMBER = 1;

var CONST_CHECKED_COLUMN_NUMBER = 1;


var CONST_EXPORT_SCOPE_ENUM = Object.freeze({"INCLUDE_ALL": 1, "INCLUDE_ONLY_CHECKED": 2});
var CONST_PROCESS_STATUS_ENUM = Object.freeze({"SUCCESS": 0, "WARNING": 1, "ERROR": 3});
var CONST_DATA_IMPORT_SHEET_NAME = "Data Import Sandbox";

var CONST_HEAVY_LOAD_THRESHOLD = 2000;
var CONST_HEAVY_LOAD_DATARAPTOR_NAME = "EPC on Steroids_Load Chunks for Offline Processing";