var CONST_APPLICATION_VERSION = "0.5";
var CONST_APPLICATION_NAME    = "EPC on Steroids";

var CONST_ACCESS_TOKEN_PROPERTY_NAME = "accessToken";
var CONST_INSTANCE_URL_PROPERTY_NAME = "instanceUrl";
var STRING_EMPTY_STRING_CONST = "";


var CONST_FIRST_HEADER_ROW_NUMBER = 1;
var CONST_FIRST_HEADER_COLUMN_NUMBER = 1;
var CONST_LAST_HEADER_ROW_NUMBER = 2;

var CONST_FIRST_DATA_ROW_NUMBER = 3;
var CONST_FIRST_DATA_COLUMN_NUMBER = 1;

var CONST_CHECKED_COLUMN_NUMBER = 1;


var CONST_EXPORT_SCOPE_ENUM = Object.freeze({"INCLUDE_ALL": 1, "INCLUDE_ONLY_CHECKED": 2});
var CONST_DATA_IMPORT_SHEET_NAME = "Data Import Sandbox";